### ISSUE TITLE
0.7x patch no longer applicable for the new 0.80+ code

### ISSUE THREAD

**Issue by h31p** [jjjordan/putty-italics#3]
due to notable changes in window logic, this patch no longer fits the latest putty code.
can we hope on rework? thank you.

**Comment by jjjordan** [comment]
I'll have a look.

**Comment by jjjordan** [comment]
Are you able to build with #4? I quickly synced to update the patches but am not currently able to test it. Otherwise I can look at it in about a week.

EDIT: Here's a [quicker link to 0.80](https://github.com/jjjordan/putty-italics/blob/update-79-and-80/italics-0.80.patch)

**Comment by h31p** [comment]
> Are you able to build with #4? I quickly synced to update the patches but am not currently able to test it. Otherwise I can look at it in about a week.

with 0.80-release sources it's able to build and working, thanks!

but with git-cloned latest devel sources - there are rejected hunks, so the story is not over :)

closing for now, thanks again for the great job!

**Comment by jjjordan** [comment]
Thanks, I've merged it.
